# latest Ubuntu image as the base
FROM ubuntu:latest

# Update APT package lists and upgrade installed packages
RUN apt-get update && apt-get upgrade -y

# Command run when the container starts
CMD echo "Hello, World!"
